//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Co_so
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Co_so()
        {
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_con_giong_vat_nuoi { get; set; }
        public Nullable<int> id_animal { get; set; }
        public Nullable<int> id_tinh_phoi { get; set; }
        public Nullable<int> id_loai_hinh { get; set; }
        public Nullable<int> id_user_dung_dau { get; set; }
        public Nullable<int> id_xa { get; set; }
        public Nullable<int> id_huyen { get; set; }
        public Nullable<int> id_gen { get; set; }
    
        public virtual animal animal { get; set; }
        public virtual Con_giong_vat_nuoi Con_giong_vat_nuoi { get; set; }
        public virtual Gen_dv Gen_dv { get; set; }
        public virtual Huyen Huyen { get; set; }
        public virtual Loai_hinh_user Loai_hinh_user { get; set; }
        public virtual Tinh_phoi_uu_trung_aptrung Tinh_phoi_uu_trung_aptrung { get; set; }
        public virtual Xa Xa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
