//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Co_so_thuc_an_chan_nuoi
    {
        public int id { get; set; }
        public string name { get; set; }
        public int id_chung_nhan { get; set; }
        public int id_user_dung_dau { get; set; }
        public int id_loai_hinh { get; set; }
        public int id_xa { get; set; }
        public int id_huyen { get; set; }
    
        public virtual Loai_hinh_user Loai_hinh_user { get; set; }
        public virtual Xa Xa { get; set; }
    }
}
