//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ktpmudEntities1 : DbContext
    {
        public ktpmudEntities1()
            : base("name=ktpmudEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animal> animals { get; set; }
        public virtual DbSet<Co_so> Co_so { get; set; }
        public virtual DbSet<Co_so_thuc_an_chan_nuoi> Co_so_thuc_an_chan_nuoi { get; set; }
        public virtual DbSet<Con_giong_vat_nuoi> Con_giong_vat_nuoi { get; set; }
        public virtual DbSet<Gen_dv> Gen_dv { get; set; }
        public virtual DbSet<Huyen> Huyens { get; set; }
        public virtual DbSet<loai_hinh_tac_dong> loai_hinh_tac_dong { get; set; }
        public virtual DbSet<Loai_hinh_user> Loai_hinh_user { get; set; }
        public virtual DbSet<quy_mo> quy_mo { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<thanh_phan_thuc_an> thanh_phan_thuc_an { get; set; }
        public virtual DbSet<Tinh_phoi_uu_trung_aptrung> Tinh_phoi_uu_trung_aptrung { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Xa> Xas { get; set; }
        public virtual DbSet<log> logs { get; set; }
    }
}
