//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTPMUD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xa()
        {
            this.Co_so = new HashSet<Co_so>();
            this.Co_so_thuc_an_chan_nuoi = new HashSet<Co_so_thuc_an_chan_nuoi>();
            this.users = new HashSet<user>();
        }
    
        public int id_xa { get; set; }
        public string name { get; set; }
        public Nullable<int> id_Huyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Co_so> Co_so { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Co_so_thuc_an_chan_nuoi> Co_so_thuc_an_chan_nuoi { get; set; }
        public virtual Huyen Huyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
